{% set name = "OpenSees" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenSees/OpenSees/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fa805d2db131939b06042568f56b875c40d80a46c96b0d60dbfbfa0fbbceaaa6

build:
  skip: True  # [not linux]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - openmpi
  host:
    - python
    - pip
    - setuptools
    - mumps
    - eigen
    - hdf5
    - openmpi
    - scalapack
    - tk
    - mysql
    - zlib
    - mkl
    - mkl-include
    - mkl-devel
    - metis
    - libscotch
    - libaec
    - libcurl
    - openssl    
  run:
    - scalapack
    - python
    - mkl

test:
  commands:
    - test -f $PREFIX/bin/OpenSees  # [unix]

  imports:
    - opensees

about:
  home: https://opensees.berkeley.edu/
  summary: 'Simulate the performance of structural and geotechnical systems 
     subjected to earthquakes'
  description: |
    OpenSees is a software framework for developing applications
     to simulate the performance of structural and geotechnical systems 
     subjected to earthquakes. 
     The goal of the OpenSees development is to improve the modeling 
     and computational simulation in earthquake engineering 
     through open-source development.
     The development of OpenSees was sponsored by 
     the Pacific Earthquake Engineering Research Center.
  license: BSD-4-Clause-UC
  license_family: BSD
  license_file: COPYRIGHT
  doc_url: https://opensees.github.io/OpenSeesDocumentation/
  dev_url: https://github.com/OpenSees/OpenSees

extra:
  recipe-maintainers:
    - ldallolio
